server:
  port: 23000
# Zero MQ Configuration
zeromq:
  address-port: tcp://*:25566
# MQTT Sender Details
mqtt:
  broker: localhost
  password: guest
  port: 1883
  topic: coreData
  user-name: guest
  
# Consul Health Check
spring:
  cloud:
    consul:
      discovery:
        health-check-path: /api/v1/ping
